Create LICENSE
umgefahren/server-language-benchmark pull request #18
Opened 2022-04-07 21:50 UTC by umgefahren

2022-04-07 21:51 UTC, tectrixer approved these changes
Nice, I like MIT

2022-04-07 23:09 UTC, Zollerboy1 approved these changes

2022-04-08 07:51 UTC, vypxl commented
I would like to be mentioned in the license. Please add all contributors separately or say "& contributors"

2022-04-08 07:53 UTC, Zollerboy1 commented
Maybe a separate Contributors.txt file?

2022-04-08 11:47 UTC, vypxl approved these changes

2022-04-08 11:47 UTC, merged

2022-04-08 11:48 UTC, tectrixer commented on CONTRIBUTERS.txt
> +tectrixer
Please spell TecTrixer

2022-04-08 11:49 UTC, tectrixer requested changes
Please change my name, see single line comment